name: Default
on: [push, pull_request]

jobs:
  Default:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Test
        run: cargo test --release